### ISSUE TITLE
"Rubicon" name collides with existing project in the Python ecosystem

### ISSUE THREAD

**Issue by freakboy3742** [capitalone/rubicon-ml#85]
**Describe the bug**

I was just made aware of this project via a PyCon US announcement email.

The problem: the name you've chosen for this project collides with an existing project in the Python ecosystem.

I've been using the name Rubicon in the Python ecosystem since 2014. I'm the owner of the Rubicon record in PyPI, as well as some related projects:

 * https://pypi.org/project/rubicon/
 * https://pypi.org/project/rubicon-java/
 * https://pypi.org/project/rubicon-objc/

These projects are in active use in the Python community, and the Java subproject received funding (indirectly) from the PSF through their support of the BeeWare Android port.

I can only assume this is something you were at least partially aware of, because you've chosen the name `rubicon-ml` for your PyPI package, and [changed the name of the package in setup.py](#10).

Although the projects are in a different domain (language bridging vs numerical processing), I'd argue there is potential for confusion since they're both active projects in the same language ecosystem, and there is some usage of BeeWare tooling in the numerical processing community.

I humbly request you choose a different name for your project that doesn't collide with my pre-existing usage.

**Comment by srilatharanganathan** [comment]
@freakboy3742 , Thanks for the issue. We will take care of it.

**Comment by gforsyth** [comment]
Thanks for raising this, @freakboy3742 !  

We used the name `rubicon` internally for a while before open sourcing the project -- when I noticed that the PyPI record was taken I took a quick look around and thought that it was not in active use, since there's just the initial 0.0.0 release.  I did not do my due diligence and dig any further than that and I apologize, as a cursory googling would've turned up the BeeWare connection.

If we change the project name to match our current PyPI and conda-forge records (`rubicon-ml`) -- would that sufficiently disambiguate things?  I recognize that that also matches your subproject naming scheme, but hopefully the original `ML` language is sufficiently out-of-use to avoid further confusion?

**Comment by freakboy3742** [comment]
My *ideal* solution would be a full rename; however, I appreciate that would cause a whole bunch of headaches. 

A rename to `rubicon-ml` sounds like the best "low impact" outcome.

If you're able to drop a mention in your README to the effect of "If you're looking for Rubicon, the Java/ObjC Python bridge, see <links to the projects>", that would also be appreciated.

**Comment by gforsyth** [comment]
Much appreciated @freakboy3742 -- we will definitely drop a note in the README to redirect any lost souls.  We'll leave this issue open to be closed by the PR renaming the module / doc references.

**Comment by mmccarty** [comment]
Thanks @freakboy3742! - We will prioritize this right away.

**Comment by joe-wolfe21** [comment]
@freakboy3742 the library/readme/docs have been updated  🎉

**Comment by freakboy3742** [comment]
👍 Thanks!
